### ISSUE TITLE
当文件不存在时，执行压缩会导致闪退，Android 11

### ISSUE THREAD

**Issue by xiaoyvyv** [forJrking/KLuban#10]
当文件不存在时，执行压缩会导致应用闪退，Android 11，onError有回调，导致闪退的异常是：java.io.FileNotFoundException: No content provider: xxx

**Comment by xiaoyvyv** [comment]
onError回调的信息为：Parent job is Cancelling;xxxx。FileNotFoundException 之类的异常应该是内部没处理直接抛出来了吗

**Comment by xiaoyvyv** [comment]
还有一个问题 ：onCompletion 在 onSuccess 之前回调了。

**Comment by xiaoyvyv** [comment]
```java
2021-04-01 11:25:22.119 31698-31698/com.yangtzeu E/CrashReport: #++++++++++Record By Bugly++++++++++#
2021-04-01 11:25:22.119 31698-31698/com.yangtzeu E/CrashReport: # You can use Bugly(http:\\bugly.qq.com) to get more Crash Detail!
2021-04-01 11:25:22.119 31698-31698/com.yangtzeu E/CrashReport: # PKG NAME: com.yangtzeu
2021-04-01 11:25:22.119 31698-31698/com.yangtzeu E/CrashReport: # APP VER: 5.1
2021-04-01 11:25:22.119 31698-31698/com.yangtzeu E/CrashReport: # SDK VER: 3.3.3
2021-04-01 11:25:22.119 31698-31698/com.yangtzeu E/CrashReport: # LAUNCH TIME: 2021-04-01 11:24:49
2021-04-01 11:25:22.119 31698-31698/com.yangtzeu E/CrashReport: # CRASH TYPE: JAVA_CRASH
2021-04-01 11:25:22.119 31698-31698/com.yangtzeu E/CrashReport: # CRASH TIME: 2021-04-01 11:25:22
2021-04-01 11:25:22.119 31698-31698/com.yangtzeu E/CrashReport: # CRASH PROCESS: com.yangtzeu
2021-04-01 11:25:22.119 31698-31698/com.yangtzeu E/CrashReport: # CRASH THREAD: main
2021-04-01 11:25:22.119 31698-31698/com.yangtzeu E/CrashReport: # REPORT ID: c29b4541-018f-40d4-b4e5-6023f9b74437
2021-04-01 11:25:22.119 31698-31698/com.yangtzeu E/CrashReport: # CRASH DEVICE: M2011K2C UNROOT
2021-04-01 11:25:22.119 31698-31698/com.yangtzeu E/CrashReport: # RUNTIME AVAIL RAM:3148906496 ROM:45396619264 SD:45396619264
2021-04-01 11:25:22.119 31698-31698/com.yangtzeu E/CrashReport: # RUNTIME TOTAL RAM:7653187584 ROM:113176981504 SD:113176981504
2021-04-01 11:25:22.119 31698-31698/com.yangtzeu E/CrashReport: # CRASH STACK: 
2021-04-01 11:25:22.119 31698-31698/com.yangtzeu E/CrashReport: java.io.FileNotFoundException: No content provider: asfasf
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1996)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1825)
        at android.content.ContentResolver.openInputStream(ContentResolver.java:1502)
        at com.forjrking.lubankt.Luban$load$6$1.openInternal(Luban.kt:98)
        at com.forjrking.lubankt.io.InputStreamAdapter.rewindAndGet(InputStreamAdapter.kt:26)
        at com.forjrking.lubankt.Builder$compress$2.invokeSuspend(Luban.kt:253)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at k.a.x0.run(DispatchedTask.kt:106)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
        at com.forjrking.lubankt.CompressThreadFactory$newThread$thread$1.run(Luban.kt:390)
2021-04-01 11:25:22.119 31698-31698/com.yangtzeu E/CrashReport: #++++++++++++++++++++++++++++++++++++++++++#
2021-04-01 11:25:22.235 31698-31698/com.yangtzeu E/CrashReport: sys default last handle start!
```

**Comment by forJrking** [comment]
1.0.5 版本  Android 11模拟器跑如下代码测试文件不存在崩溃问题
```
        val file: File = File("D://t.jpg")
//        val uri: Uri = Uri.fromFile(file)
        Luban.with(this)                        
                .load(file)                         
                .format(Bitmap.CompressFormat.PNG)      //压缩后输出文件格式 支持 JPG,PNG,WEBP
                .ignoreBy(200)                     //期望大小,大小和图片呈现质量不能均衡所以压缩后不一定小于此值,
                .quality(95)                     //质量压缩系数  0-100
                .compressObserver {
                    onStart = {
                        //Log.d(TAG, "onStart: ")
                    }
                    onCompletion = {
                        Log.d(TAG, "onCompletion")
                    }
                    onSuccess = {
                        Toast.makeText(this@MainActivity, "file" + it.name, Toast.LENGTH_LONG).show()
                        mIv!!.setImageURI(Uri.fromFile(it))
                    }
                    onError = { a, _ ->
                        Log.e(TAG, a.toString())
                    }
                }.launch()
```
输出日志：
2021-04-01 14:58:26.153 9693-9693/com.forjrking.image D/Luban: onCompletion
2021-04-01 14:58:26.153 9693-9693/com.forjrking.image E/Luban: java.io.FileNotFoundException: D:/t.jpg: open failed: ENOENT (No such file or directory)
没有出现崩溃，请检查是否为项目配置其他问题

**Comment by forJrking** [comment]
> 还有一个问题 ：onCompletion 在 onSuccess 之前回调了。

onCompletion 设计是loading的关闭用的，失败也会先调用这个然后回调失败

**Comment by xiaoyvyv** [comment]
```java
Uri uri = Uri.parse("xxxxxxxxx");
若出现这种 错误 的 uri 就会崩溃，我看源码 发现是  load()  判断为 Uri 时候，可能抛出的 FileNotFoundException 没有处理，只捕获了 IOException 
```

**Comment by xiaoyvyv** [comment]
```java
 is Uri -> {
        Checker.context.contentResolver.openInputStream(src as Uri)!!
 }
```

这段代码 可能抛出的 FileNotFoundException 没处理

**Comment by forJrking** [comment]
> ```java
>  is Uri -> {
>         Checker.context.contentResolver.openInputStream(src as Uri)!!
>  }
> ```
> 
> 这段代码 可能抛出的 FileNotFoundException 没处理

请使用1.0.7版本尝试，如果修复请帮助关闭 issues
implementation 'com.github.forJrking:KLuban:1.0.7'

**Comment by xiaoyvyv** [comment]
```
Failed to resolve: com.github.forJrking:KLuban:1.0.7

**Comment by forJrking** [comment]
> ```
> Failed to resolve: com.github.forJrking:KLuban:1.0.7
> ```

我重新发布了1.0.8  我测试可以，1.0.7不知道原因

**Comment by xiaoyvyv** [comment]
1.0.7测试通过了，不会崩溃，正常走onError
