### ISSUE TITLE
当上传某些图片的时候会出现崩溃

### ISSUE THREAD

**Issue by NeVaDaAAA** [forJrking/KLuban#4]
设备信息:小米 MIX 2S MIUI12开发版 20.9.4
Android 10 

报错信息:
com.forjrking.lubankt.io.BufferedInputStreamWrap$InvalidMarkException: Mark has been invalidated, pos: 2497492 markLimit: 5242880
	at com.forjrking.lubankt.io.BufferedInputStreamWrap.reset(BufferedInputStreamWrap.java:318)
	at com.forjrking.lubankt.Checker$getOrientation$reader$1.getOrientation(Checker.kt:117)
	at com.forjrking.lubankt.Checker.getOrientationInternal(Checker.kt:138)
	at com.forjrking.lubankt.Checker.getOrientation(Checker.kt:121)
	at com.forjrking.lubankt.CompressEngine.compress(CompressEngine.kt:48)
	at com.forjrking.lubankt.Builder$compress$2.invokeSuspend(Luban.kt:270)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
	at com.forjrking.lubankt.CompressThreadFactory$newThread$thread$1.run(Luban.kt:385)

报错图片:
![微信图片_20201208153531](https://user-images.githubusercontent.com/20659340/101453924-10bc6c80-396b-11eb-8f5d-8beab28ce2d9.jpg)

**Comment by forJrking** [comment]
#

> 设备信息:小米 MIX 2S MIUI12开发版 20.9.4
> Android 10
> 
> 报错信息:
> com.forjrking.lubankt.io.BufferedInputStreamWrap$InvalidMarkException: Mark has been invalidated, pos: 2497492 markLimit: 5242880
> at com.forjrking.lubankt.io.BufferedInputStreamWrap.reset(BufferedInputStreamWrap.java:318)
> at com.forjrking.lubankt.Checker$getOrientation$reader$1.getOrientation(Checker.kt:117)
> at com.forjrking.lubankt.Checker.getOrientationInternal(Checker.kt:138)
> at com.forjrking.lubankt.Checker.getOrientation(Checker.kt:121)
> at com.forjrking.lubankt.CompressEngine.compress(CompressEngine.kt:48)
> at com.forjrking.lubankt.Builder$compress$2.invokeSuspend(Luban.kt:270)
> at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> at java.lang.Thread.run(Thread.java:919)
> at com.forjrking.lubankt.CompressThreadFactory$newThread$thread$1.run(Luban.kt:385)
> 
> 报错图片:
> ![微信图片_20201208153531](https://user-images.githubusercontent.com/20659340/101453924-10bc6c80-396b-11eb-8f5d-8beab28ce2d9.jpg)

目前手头没有10的机器，模拟器测试没复现，发现一些问题，尽快新版本尝试修复。

**Comment by NeVaDaAAA** [comment]
感觉是参考glide造成的
[Glide 同样的 issue](https://github.com/bumptech/glide/issues/2510)

**Comment by 1322202454** [comment]
com.forjrking.lubankt.io.BufferedInputStreamWrap$InvalidMarkException: Mark has been invalidated, pos: 116284 markLimit: 5242880
2021-01-08 18:13:20.721 16129-16129/com.yizhong.interior W/System.err:     at com.forjrking.lubankt.io.BufferedInputStreamWrap.reset(BufferedInputStreamWrap.java:318)
2021-01-08 18:13:20.722 16129-16129/com.yizhong.interior W/System.err:     at com.forjrking.lubankt.Checker$getOrientation$reader$1.getOrientation(Checker.kt:117)
2021-01-08 18:13:20.722 16129-16129/com.yizhong.interior W/System.err:     at com.forjrking.lubankt.Checker.getOrientationInternal(Checker.kt:138)
2021-01-08 18:13:20.722 16129-16129/com.yizhong.interior W/System.err:     at com.forjrking.lubankt.Checker.getOrientation(Checker.kt:121)
2021-01-08 18:13:20.722 16129-16129/com.yizhong.interior W/System.err:     at com.forjrking.lubankt.CompressEngine.compress(CompressEngine.kt:51)
2021-01-08 18:13:20.722 16129-16129/com.yizhong.interior W/System.err:     at com.forjrking.lubankt.Builder$compress$2.invokeSuspend(Luban.kt:270)
2021-01-08 18:13:20.722 16129-16129/com.yizhong.interior W/System.err:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2021-01-08 18:13:20.722 16129-16129/com.yizhong.interior W/System.err:     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2021-01-08 18:13:20.722 16129-16129/com.yizhong.interior W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2021-01-08 18:13:20.722 16129-16129/com.yizhong.interior W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2021-01-08 18:13:20.722 16129-16129/com.yizhong.interior W/System.err:     at java.lang.Thread.run(Thread.java:919)
2021-01-08 18:13:20.723 16129-16129/com.yizhong.interior W/System.err:     at com.forjrking.lubankt.CompressThreadFactory$newThread$thread$1.run(Luban.kt:385)

我这是同一张图片换了两个手机了  都是报错

**Comment by forJrking** [comment]
> getOrientationInternal

提供下机型和图片，目前这个问题我还没复现。会尝试修复

**Comment by 1322202454** [comment]
1加 7Pro   Android 10

**Comment by 1322202454** [comment]
图片我私聊你

**Comment by 1322202454** [comment]
要不你家我QQ1322202454  或者  你把QQ给我我加你

**Comment by forJrking** [comment]
1.0.5 版本修复此问题，此问题在此关闭。。后续出现请提 issues

**Comment by IdioticMadman** [comment]
@forJrking 我这边又出现此类问题。麻烦是否可以提供一下commit。看下修改

**Comment by IdioticMadman** [comment]
看了一下，是因为图片过大。超过了markLimit后，在进行inputStream进行reset就会有这个问题。这个markLimit是不是应该和文件同大小呢？

**Comment by MirkoWu** [comment]
> 看了一下，是因为图片过大。超过了markLimit后，在进行inputStream进行reset就会有这个问题。这个markLimit是不是应该和文件同大小呢？

请问这个有解决吗？
